= Roboquant Archetype
This is a Maven Archetype project for roboquant called `roboquant-quickstart`. It helps to quickly start a new algo-trading project.

== Running it
You can create your own new algo-trading application from scratch by running the following command:

[source,shell]
----
mvn archetype:generate                       \
-DarchetypeGroupId=org.roboquant             \
-DarchetypeArtifactId=roboquant-quickstart   \
-DarchetypeVersion=1.3.0                     \
-DgroupId=org.mydomain                       \
-DartifactId=myapp                           \
-Dversion=1.0-SNAPSHOT
----

You should substitute the last three parameters with your own configuration.

== Installing Archetype from source
After you have cloned the GitHub repo, you can locally install an archetype just like any other Maven artefact.

[source,shell]
----
mvn install
----

You can run the archetype to create a new roboquant project using the following command:

[source,shell]
----
mvn archetype:generate -Dfilter=roboquant-quickstart
----

The `-Dfilter` parameter is optional, but makes it easier to locate the archetype

To run the archetype without the manual input, you can use the command with following additional parameters:

